version: '3.3'

services:

  urbackup:
    image: uroni/urbackup-server:latest
    container_name: urbackup
    restart: unless-stopped
    environment:
      - PUID=1000 
      - PGID=1000  
      - TZ=Europe/Madrid 
    ports:
      - "55413:55413"
      - "55414:55414"
      - "55415:55415"            
      - "35623:35623/udp"  
    volumes:
      - ./urba/database:/var/urbackup
      - ./urba/backup:/backups

